"""`returns-manager seed demo` (P1 scope): private buckets, the two sample orgs, demo users and memberships.

Users are created through the Supabase Auth admin API (via storage.service_client, the only holder of the
service-role key). Each run sets fresh random passwords and writes them to the git-ignored
`.env.demo-users` at the repository root; they are printed once. Orders and products are seeded in P2.
"""

from __future__ import annotations

import asyncio
import secrets
import string
from dataclasses import dataclass
from pathlib import Path

from returns_manager.config import REPO_ROOT, Settings
from returns_manager.db.pool import Database
from returns_manager.security.roles import Role
from returns_manager.storage.photos import PhotoStorage
from returns_manager.storage.service_client import ServiceCredentials

DEMO_ORGS = {"org_demo_alpha": "Demo Alpha (synthetic)", "org_demo_bravo": "Demo Bravo (synthetic)"}


@dataclass(frozen=True)
class DemoUser:
    org_id: str
    label: str
    role: Role

    @property
    def email(self) -> str:
        return f"{self.label}.{self.org_id}@example.com"


DEMO_USERS: tuple[DemoUser, ...] = (
    DemoUser("org_demo_alpha", "op_eli", Role.OPERATOR),
    DemoUser("org_demo_alpha", "op_dana", Role.OPERATOR),
    DemoUser("org_demo_alpha", "rev_priya", Role.REVIEWER),
    DemoUser("org_demo_alpha", "adm_alpha", Role.ADMIN),
    DemoUser("org_demo_bravo", "op_chen", Role.OPERATOR),
    DemoUser("org_demo_bravo", "rev_sam", Role.REVIEWER),
    DemoUser("org_demo_bravo", "adm_bravo", Role.ADMIN),
)

DEMO_USERS_FILE = REPO_ROOT / ".env.demo-users"


@dataclass(frozen=True)
class SeededUser:
    user: DemoUser
    user_id: str
    password: str


def _password() -> str:
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(24))


async def _find_user_id(creds: ServiceCredentials, email: str) -> str | None:
    page = 1
    while True:
        resp = await creds.auth_admin("GET", f"/admin/users?page={page}&per_page=200")
        resp.raise_for_status()
        users = resp.json().get("users", [])
        for u in users:
            if (u.get("email") or "").lower() == email.lower():
                return str(u["id"])
        if len(users) < 200:
            return None
        page += 1


async def ensure_user(creds: ServiceCredentials, user: DemoUser) -> SeededUser:
    password = _password()
    resp = await creds.auth_admin(
        "POST", "/admin/users", json={"email": user.email, "password": password, "email_confirm": True}
    )
    if resp.status_code in (200, 201):
        return SeededUser(user, str(resp.json()["id"]), password)
    user_id = await _find_user_id(creds, user.email)
    if user_id is None:
        resp.raise_for_status()
        raise RuntimeError(f"could not create or find demo user {user.email}")
    upd = await creds.auth_admin("PUT", f"/admin/users/{user_id}", json={"password": password})
    upd.raise_for_status()
    return SeededUser(user, user_id, password)


async def seed(db: Database, settings: Settings, users_file: Path = DEMO_USERS_FILE) -> list[SeededUser]:
    storage = PhotoStorage(settings)
    await storage.ensure_buckets()
    for org_id, name in DEMO_ORGS.items():
        async with db.transaction(org_id) as conn:
            await conn.execute(
                "INSERT INTO rm.organizations (org_id, name) VALUES (%s, %s) ON CONFLICT (org_id) DO NOTHING",
                (org_id, name),
            )
    creds = ServiceCredentials(settings)
    seeded = [await ensure_user(creds, u) for u in DEMO_USERS]
    for s in seeded:
        async with db.transaction(s.user.org_id) as conn:
            await conn.execute(
                """INSERT INTO rm.memberships (user_id, org_id, role, operator_label)
                   VALUES (%s, %s, %s, %s)
                   ON CONFLICT (user_id, org_id) DO UPDATE SET role = EXCLUDED.role,
                                                               operator_label = EXCLUDED.operator_label""",
                (s.user_id, s.user.org_id, s.user.role.value, s.user.label),
            )
    lines = [
        "# Demo users (synthetic). Generated by `returns-manager seed demo`. Git-ignored. Do not commit."
    ]
    for s in seeded:
        key = f"{s.user.org_id}_{s.user.label}".upper()
        lines += [
            f"{key}_EMAIL={s.user.email}",
            f"{key}_PASSWORD={s.password}",
            f"{key}_ROLE={s.user.role.value}",
        ]
    text = "\n".join(lines) + "\n"
    await asyncio.to_thread(users_file.write_text, text, encoding="utf-8", newline="\n")
    return seeded
